July, August and September 23
ErickWendel/timeline pull request #39
Opened 2023-09-07 05:54 UTC by jessilyneh

Talks: 134, Posts: 365, Videos: 131, Projects: 19

2023-09-07 15:08 UTC, ErickWendel commented
@jessilyneh as talks precisam ter o numero aproximado de participantes, as que você não souber é só me pedir no discord.

2023-09-07 15:14 UTC, ErickWendel requested changes

2023-09-07 15:14 UTC, ErickWendel commented on resources/talks.json
> +    "abstract": "O próximo nível para desenvolvedores Web:Machine Learning em Navegadores",
replicou?

2023-09-07 15:14 UTC, ErickWendel commented on resources/talks.json
> +    "slides": "https://drive.google.com/drive/folders/17may8spjii6wlcHSGDIsjBKJ82ZCZyLb",
https://bit.ly/o-segredo-para-processar-terabytes-em-js

2023-09-07 15:14 UTC, ErickWendel commented on resources/talks.json
> +    "video": "https://portal.gitnation.org/contents/bun-deno-nodejs-recreating-a-javascript-runtime-from-scratch-understand-magic-behind-nodejs",
git nation em oslo? Aqui o video: https://youtu.be/uNGDW3snVyA?si=tepKjmfUE-LmkpFI

2023-09-07 15:14 UTC, ErickWendel commented on resources/talks.json
> +    "title": "Bun?Deno?Node.js?Recreating a JS Runtime from scratch",
revisar os espacós nos titulos

2023-09-07 15:14 UTC, ErickWendel commented on resources/videos.json
> +    "abstract": "Solos que guitarra não vão me conquistar",
que descrição é essa gsus 😂

2023-09-07 19:53 UTC, ErickWendel commented
esse PR contempla https://github.com/ErickWendel/timeline/pull/37 ?

2023-09-07 23:51 UTC, jessilyneh commented on resources/talks.json
> +    "abstract": "O próximo nível para desenvolvedores Web:Machine Learning em Navegadores",
ja gerei uma descricao

2023-09-07 23:52 UTC, jessilyneh commented on resources/talks.json
> +    "slides": "https://drive.google.com/drive/folders/17may8spjii6wlcHSGDIsjBKJ82ZCZyLb",
vou revisar os links dos slides em geral

2023-09-08 01:45 UTC, jessilyneh commented on resources/videos.json
> +    "abstract": "Solos que guitarra não vão me conquistar",
estava la na descrição do podcast, eu não invento nada hahaha é que quando eu comecei a fazer essas contribuições, você falou que era so pegar a frase seguinte, ai eu tenho feito isso ate hoje hahaha
Aqui, como esta la
![image](https://github.com/ErickWendel/timeline/assets/37668064/099400b0-8617-4551-8759-ac45f671931a)

2023-09-08 01:47 UTC, jessilyneh commented on resources/videos.json
> +    "abstract": "Solos que guitarra não vão me conquistar",
ow, agora que eu vi, os malucos desse podcast ai tao falando que voce consertou o Java hahahaha

2023-09-11 20:10 UTC, ErickWendel commented on resources/videos.json
> +    "abstract": "Solos que guitarra não vão me conquistar",
meu deus hahaha

2023-11-15 17:45 UTC, closed without merging