October/nov 23
ErickWendel/timeline pull request #40
Opened 2023-11-15 17:33 UTC by jessilyneh

2023-11-17 19:29 UTC, ErickWendel requested changes

2023-11-17 19:29 UTC, ErickWendel commented on resources/talks.json
> +    "abstract": "Explore a journey through JS runtimes, from Node.js to Deno, and learn how to build your own custom runtime",
mudou de nome pq?

2023-11-17 19:29 UTC, ErickWendel commented on resources/videos.json
> +    },
remover alterações de formatação

2023-11-17 19:31 UTC, ErickWendel commented
@jessilyneh senti falta de colocar a quantidade de pessoas em cada palestra no campo `"reach": 0`

2023-11-17 19:47 UTC, jessilyneh commented on resources/talks.json
> +    "abstract": "Explore a journey through JS runtimes, from Node.js to Deno, and learn how to build your own custom runtime",
espaçamento apenas

2023-11-17 21:23 UTC, jessilyneh commented
> @jessilyneh senti falta de colocar a quantidade de pessoas em cada palestra no campo `"reach": 0`

ok mas, seu front espera isso? Nao vai quebrar nada? Vou acrescentar em todas as palestras entao, desde a primeira registrada

2023-11-27 16:28 UTC, ErickWendel approved these changes
reach deveria estar no corpo não no sub objeto evento, mas vou corrigir aqui e atualizar na main thaaanks

2023-11-27 16:28 UTC, merged